import { chromium } from 'playwright'
import jwt from 'jsonwebtoken'
import { readFileSync } from 'fs'
for (const line of readFileSync('.env','utf8').split('\n')) { const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/); if(m) process.env[m[1]]=m[2].replace(/^["']|["']$/g,'') }
const { sql } = await import('./backend/src/services/db.ts')
const u = (await sql`SELECT id, tenant_id, role FROM users WHERE tenant_id='delpat' AND role='owner' AND deleted_at IS NULL LIMIT 1`)[0]
const token = jwt.sign({ kind:'user', tenant_id:u.tenant_id, user_id:u.id, role:u.role }, process.env.JWT_SECRET, { expiresIn:'1h' })
const b = await chromium.launch({ headless:true })
const ctx = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true })
const p = await ctx.newPage()
p.on('pageerror', e=>console.log('PAGEERR:', e.message))
await p.addInitScript(([t,tid])=>{localStorage.setItem('crm_auth_token',t);localStorage.setItem('crm_tenant_id',tid)},[token,u.tenant_id])
await p.goto('http://localhost:5173/?autologin&ws=delpat'); await p.waitForTimeout(3500)
const url = () => p.url().replace('http://localhost:5173/','')
console.log('1 launch        :', url())
await p.locator('.tabbar a').filter({ hasText:'Leads' }).first().click(); await p.waitForTimeout(1200)
console.log('2 tap Leads     :', url())
await p.locator('.tbl tbody tr, .rcard, .q-row').first().click(); await p.waitForTimeout(1500)
console.log('3 open a record :', url())
await p.reload(); await p.waitForTimeout(3500)
console.log('4 after reload  :', url())
console.log('  still on record?', await p.locator('.rh-actbar').count() > 0)
await p.goBack(); await p.waitForTimeout(1200)
console.log('5 back          :', url(), '| record open?', await p.locator('.rh-actbar').count() > 0)
await p.goBack(); await p.waitForTimeout(1200)
console.log('6 back again    :', url())
await p.goBack(); await p.waitForTimeout(1200)
console.log('7 back at root  :', url())
console.log('  toast shown   :', (await p.locator('.toast-text').allInnerTexts()).join(' | ') || 'NONE')
await b.close(); process.exit(0)
