process.env.APP_ENV = 'development';
const { databaseUrl } = await import('./services/env');
const postgres = (await import('postgres')).default;
const sql = postgres(databaseUrl(), { max: 1, ssl: 'require' });
console.log(await sql`SELECT value->'stages' st, value->'ownerStages' os, value->>'timezone' tz FROM crm_settings WHERE tenant_id='delpat' AND key='default'`);
console.log(await sql`SELECT u.name, u.role, (SELECT count(*)::int FROM crm_leads l WHERE l.tenant_id='delpat' AND l.agent_id=u.id) leads, (SELECT count(*)::int FROM crm_owners o WHERE o.tenant_id='delpat' AND o.agent_id=u.id) owners, u.id FROM users u WHERE u.tenant_id='delpat' AND u.deleted_at IS NULL`);
console.log(await sql`SELECT coalesce(stage,'-') s, count(*)::int FROM crm_leads WHERE tenant_id='delpat' GROUP BY 1 ORDER BY 2 DESC`);
console.log(await sql`SELECT coalesce(stage,'-') s, count(*)::int FROM crm_owners WHERE tenant_id='delpat' GROUP BY 1 ORDER BY 2 DESC`);
console.log((await sql`SELECT column_name FROM information_schema.columns WHERE table_name='activities'`).map(c=>c.column_name).join(','));
console.log(await sql`SELECT count(*)::int FROM crm_timeline_events WHERE tenant_id='delpat' AND timestamp > now() - interval '3 days' AND coalesce(author,'System') NOT IN ('System','Import')`);
await sql.end();
